/**
 * AutoDimensionEngine — tự động ghi kích thước
 */
class AutoDimensionEngine {
  static DRAW_COMMANDS = new Set([
    'DRAW_LINE', 'DRAW_CIRCLE', 'DRAW_RECTANGLE', 'DRAW_ARC', 'DRAW_POLYLINE'
  ]);

  static dimensionEntity(app, entity, options = {}) {
    if (entity.type === 'DIMENSION') return [];
    if (!options.force && AutoDimensionEngine._hasDimensions(app, entity.id)) return [];

    const dims = app.cadCore.dimensions.autoDimension(entity);
    if (!dims) return [];
    const list = Array.isArray(dims) ? dims : [dims];
    for (const d of list) {
      d.sourceEntityId = entity.id;
      d.autoGenerated = true;
      app.drawing.addEntity(d);
      app.cadCore.history?.push({ type: 'ADD_ENTITY', entity: d });
    }
    app.requestRender();
    return list;
  }

  static onCommandResult(app, command, result) {
    if (!app.drawing.view.showDimensions) return;
    if (!AutoDimensionEngine.DRAW_COMMANDS.has(String(command).toUpperCase())) return;
    if (result.entity) {
      AutoDimensionEngine.dimensionEntity(app, result.entity);
    }
  }

  static dimensionAll(app) {
    const entities = app.drawing.getVisibleEntities(app.layerManager);
    const added = [];
    for (const e of entities) {
      if (['LINE', 'RECTANGLE', 'CIRCLE', 'POLYLINE'].includes(e.type)) {
        const dims = AutoDimensionEngine.dimensionEntity(app, e);
        added.push(...dims);
      }
    }
    return { success: true, count: added.length };
  }

  static dimensionSelection(app) {
    const selected = app.selectionManager.getSelected();
    if (!selected.length) return { success: false, message: 'Chọn đối tượng trước' };
    let count = 0;
    for (const e of selected) {
      const dims = AutoDimensionEngine.dimensionEntity(app, e);
      count += dims.length;
    }
    return { success: true, count };
  }

  static _hasDimensions(app, entityId) {
    return app.drawing.entities.some(
      e => e.type === 'DIMENSION' && e.sourceEntityId === entityId
    );
  }
}
