/**
 * AutoDimensionEngine — hiển thị kích thước tự động (nhãn đè, không tạo entity DIMENSION)
 */
class AutoDimensionEngine {
  static DRAW_COMMANDS = new Set([
    'DRAW_LINE', 'DRAW_CIRCLE', 'DRAW_RECTANGLE', 'DRAW_ARC', 'DRAW_POLYLINE'
  ]);

  static dimensionEntity(app, entity, options = {}) {
    if (entity.type === 'DIMENSION') return [];
    app.requestRender();
    return EntityDimensionOverlay.buildLabels(entity, app.cadCore.dimensions, app.drawing.unit);
  }

  static onCommandResult(app, command, result) {
    if (!app.drawing.view.showDimensions) return;
    if (!AutoDimensionEngine.DRAW_COMMANDS.has(String(command).toUpperCase())) return;
    if (result.entity) app.requestRender();
  }

  static dimensionAll(app) {
    AutoDimensionEngine.purgeAutoDimensions(app);
    app.requestRender();
    const count = EntityDimensionOverlay.countLabels(
      app.drawing, app.layerManager, app.cadCore.dimensions
    );
    return { success: true, count };
  }

  static dimensionSelection(app) {
    const selected = app.selectionManager.getSelected();
    if (!selected.length) return { success: false, message: 'Chọn đối tượng trước' };
    app.requestRender();
    let count = 0;
    for (const e of selected) {
      count += EntityDimensionOverlay.buildLabels(e, app.cadCore.dimensions, app.drawing.unit).length;
    }
    return { success: true, count };
  }

  /** Xóa dimension entity tự sinh cũ (trước khi chuyển sang nhãn đè) */
  static purgeAutoDimensions(app) {
    const stale = app.drawing.entities.filter(e => e.type === 'DIMENSION' && e.autoGenerated);
    for (const e of stale) app.drawing.removeEntity(e);
    return stale.length;
  }
}
