/**
 * ModeConversionEngine — tự động chuyển đổi 2D ↔ 3D khi đổi chế độ xem
 */
class ModeConversionEngine {
  static DEFAULT_EXTRUDE_HEIGHT = 1;

  static onEnter3D(app) {
    const stats = { created: 0, updated: 0 };
    const bySource = ModeConversionEngine._mapBySource2D(app.drawing.entities3D);

    for (const e2 of app.drawing.entities) {
      if (e2.autoGenerated && e2.linked3DId) continue;

      const profile = MeshFactory3D.profileFrom2DEntity(e2);
      if (!profile) continue;

      let e3 = bySource.get(e2.id);
      if (e3) {
        ModeConversionEngine._refresh3DFrom2D(e3, e2, profile);
        stats.updated++;
      } else {
        e3 = ExtrudeEngine3D.from2DEntity(
          e2,
          ModeConversionEngine._getHeight(e2),
          { name: `${e2.type}` }
        );
        if (e3) {
          app.drawing.addEntity3D(e3);
          bySource.set(e2.id, e3);
          stats.created++;
        }
      }
      if (e3) {
        e3.params._syncPos = { x: e3.position.x, z: e3.position.z };
      }
    }

    return stats;
  }

  static onEnter2D(app) {
    const stats = { created: 0, updated: 0 };

    for (const e3 of app.drawing.entities3D) {
      if (e3.params?.source2DId) {
        if (ModeConversionEngine._refresh2DFromExtrude(app, e3)) stats.updated++;
      } else if (e3.params?.linked2DId) {
        if (ModeConversionEngine._refresh2DFootprint(app, e3)) stats.updated++;
      } else {
        const e2 = ModeConversionEngine._create2DFootprint(app, e3);
        if (e2) {
          e3.params.linked2DId = e2.id;
          stats.created++;
        }
      }
    }

    return stats;
  }

  static _mapBySource2D(entities3D) {
    const map = new Map();
    for (const e3 of entities3D) {
      if (e3.params?.source2DId) map.set(e3.params.source2DId, e3);
    }
    return map;
  }

  static _getHeight(e2) {
    return e2.extrudeHeight || ModeConversionEngine.DEFAULT_EXTRUDE_HEIGHT;
  }

  static _refresh3DFrom2D(e3, e2, profile) {
    e3.params.profile = profile;
    e3.params.height = ModeConversionEngine._getHeight(e2);
    e3.position.y = e3.params.height / 2;
    e3.markDirty();
  }

  static _refresh2DFromExtrude(app, e3) {
    const e2 = app.drawing.entities.find(e => e.id === e3.params.source2DId);
    if (!e2) return false;

    const last = e3.params._syncPos || { x: 0, z: 0 };
    const dx = e3.position.x - last.x;
    const dz = e3.position.z - last.z;
    if (Math.abs(dx) > 1e-6 || Math.abs(dz) > 1e-6) {
      e2.move(dx, dz);
    }

    e2.extrudeHeight = e3.params.height;
    e3.params._syncPos = { x: e3.position.x, z: e3.position.z };
    return true;
  }

  static _create2DFootprint(app, e3) {
    const layerId = app.layerManager.currentLayerId;
    let e2 = null;

    switch (e3.type) {
      case 'BOX': {
        const w = (e3.params.width || 2) * (e3.scale?.x || 1);
        const d = (e3.params.depth || 2) * (e3.scale?.z || 1);
        const cx = e3.position.x;
        const cz = e3.position.z;
        e2 = new RectangleEntity(layerId, cx - w / 2, cz - d / 2, cx + w / 2, cz + d / 2);
        break;
      }
      case 'SPHERE':
      case 'CYLINDER':
      case 'CONE': {
        const r = (e3.params.radius || e3.params.radiusTop || 1)
          * Math.max(e3.scale?.x || 1, e3.scale?.z || 1);
        e2 = new CircleEntity(layerId, e3.position.x, e3.position.z, r);
        break;
      }
      default:
        return null;
    }

    if (e2) {
      e2.linked3DId = e3.id;
      e2.autoGenerated = true;
      e2.style.lineDash = [4, 4];
      app.drawing.addEntity(e2);
    }
    return e2;
  }

  static _refresh2DFootprint(app, e3) {
    const e2 = app.drawing.entities.find(e => e.id === e3.params.linked2DId);
    if (!e2) {
      delete e3.params.linked2DId;
      return false;
    }

    if (e2.type === 'RECTANGLE' && e3.type === 'BOX') {
      const w = (e3.params.width || 2) * (e3.scale?.x || 1);
      const d = (e3.params.depth || 2) * (e3.scale?.z || 1);
      const cx = e3.position.x;
      const cz = e3.position.z;
      e2.corner1 = { x: cx - w / 2, y: cz - d / 2 };
      e2.corner2 = { x: cx + w / 2, y: cz + d / 2 };
    } else if (e2.type === 'CIRCLE') {
      const r = (e3.params.radius || e3.params.radiusTop || 1)
        * Math.max(e3.scale?.x || 1, e3.scale?.z || 1);
      e2.center = { x: e3.position.x, y: e3.position.z };
      e2.radius = r;
    } else {
      return false;
    }

    e3.params._syncPos = { x: e3.position.x, z: e3.position.z };
    return true;
  }
}
